### ISSUE TITLE
Binary cached content

### ISSUE THREAD

**Issue by fahussain** [sonyseng/json-caching-proxy#24]
First of all thank you so much for this wonderful tool. It has saved me really good amount of time during development. I have been successfully using it in one project but now when I tried to use it in another project all the cached content being served seems to be in binary, something like this:

��Q&��O<K{�cS��*���x�yV?���f��3C��<���s�9�6f����b*���2eR���Tg��F����q�0�|Nbl_����5Ay �~Kxcc�	

I can't figure out what the problem is. I have tried different node versions from 10.24.1 to 14.x. The requests when served first time are fine but later when they are served from cache the above is what I get. Any help would be much appreciated.

**Comment by fahussain** [comment]
I forced the content-encoding to gzip by overriding request headers and it started working. I guess content-encoding br is not supported.

**Comment by sonyseng** [comment]
> I forced the content-encoding to gzip by overriding request headers and it started working. I guess content-encoding br is not supported.

I know this is old and you have closed this. but the latest version now has brotli support
