### ISSUE TITLE
How can I use this in typescript

### ISSUE THREAD

**Issue by fahussain** [sonyseng/json-caching-proxy#29]
First of all thank you so much for writing this. I have been using it for some time now, and it saves me a ton of time in development.  I have a little bit of dynamic configuration based on the environment so I used the config in js file. Is there a way to use it in typescript without require?

**Comment by sonyseng** [comment]
@fahussain glad you find it useful. The last release had a bug when I moved from CJS to ESM .mjs files. I've updated the release to 2.0.1 now. You should already be able to use `import JsonCachingProxy from "json-caching-proxy";`. I mostly use this on the command line so I haven't a need to add typescript definition files. But I will try to set aside some time to add a d.ts file as soon as I can

**Comment by sonyseng** [comment]
Stale
